# .github/workflows/export-tokens-on-input.yml
name: Generate Tokens On Input from Figma

# this triggers the action when a post to "https://api.github.com/repos/:username/:repo/dispatches" comes in
on:
  repository_dispatch:
    # and the event_type property from the request body is 'update-tokens'
    types: update-tokens

jobs:
  generate_tokens:
    runs-on: macos-latest
    
    steps:
    
    # this lets us work in the actual repository 
    - uses: actions/checkout@master
    # if the folder named "input" does not exist, create it
    - name: mkdir "input" directory
      run: mkdir -p input && cd input && touch .gitkeep && git add . && cd ../
    # this creates a json file from the stringified json from the request body
    - name: create json from request body
      id: create-json
      uses: jsdaniell/create-json@1.1.2
      with:
        # it uses the name from your settings that was send as then tokenFileName parameter
        name: "design-tokens.json"
        # it uses the json string that was send as the tokens parameter
        json: ${{ github.event.client_payload.tokens }}
        # it uses the directory named "input" to store this json file (change this if you changed it above to use a different folder)
        dir: "input/"
        
    # we now initialize node to run amazon style-dictionary (SD) to compile the tokens
    
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
          # we use version 14.x of node
          node-version: '12'

    - name: Install Node Dependencies
      run: npm install
    # Running SD with newly created tokens
    - name: Build Style Dictionary
      run: npm run build

    # We may want to test if the SCSS tokens are structured correctly using a 
    # little test app. For the moment, the test is disabled.
    #- name: Update SCSS
      #run: npm run build-css

    - name: Commit Generated Platform Deliverables
      id: "auto-commit-action"
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update platform deliverables
